# Generated by Django 4.1 on 2022-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='date',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
