# Generated by Django 4.1 on 2022-09-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
    ]
