# Generated by Django 4.1 on 2022-09-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_pantry', '0002_dailymeal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(through='my_pantry.MealTable', to='my_pantry.recipe'),
        ),
        migrations.AddField(
            model_name='mealtable',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_pantry.ingredient'),
        ),
        migrations.AddField(
            model_name='mealtable',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_pantry.recipe'),
        ),
    ]
