# Generated by Django 4.1 on 2022-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pantry', '0003_mealtable_alter_ingredient_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(to='my_pantry.recipe'),
        ),
        migrations.DeleteModel(
            name='MealTable',
        ),
    ]
